sudo: required
dist: trusty

services:
  - docker

language: go

go:
  - 1.6.3

script:
  - go test -v ./...
  - env GOOS=linux GOARCH=386 go build -v github.com/Opinari/freighter
  - file freighter

after_success:

  - if [ $TRAVIS_BRANCH == 'master' ]; then
        docker build -t opinari/freighter .;
        docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push opinari/freighter;
    fi

deploy:
  provider: bintray
  file: "descriptor.json"
  user: $BINTRAY_USER
  key: $BINTRAY_KEY

notifications:
  email: false
  slack: opinari:u7vNQf4kI6z5ybUzAeh2pKmm
