sudo: required
dist: trusty

services:
  - docker

language: go

go:
  - 1.4.2

os:
  - linux
  - osx

after_success:

  - if [ $TRAVIS_BRANCH == 'master' ]; then
        docker build -t opinari/freighter .;
        docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push opinari/freighter;
    fi

notifications:
  email: false
  slack: opinari:u7vNQf4kI6z5ybUzAeh2pKmm
