sudo: required
dist: trusty

services:
  - docker

language: go

go:
  - 1.7.5

script:
  - go test -v ./...
  - env GOOS=linux GOARCH=386 go build -v github.com/opinari/freighter
  - file freighter
  - pwd
  - ls /home/travis/gopath/
  - docker build -t opinari/freighter . ;

after_success:
  - if [ $TRAVIS_BRANCH == 'master' ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push opinari/freighter;
    fi

deploy:
  provider: bintray
  file: "descriptor.json"
  user: $BINTRAY_USER
  key: $BINTRAY_KEY

notifications:
  email: false
  slack: opinari:u7vNQf4kI6z5ybUzAeh2pKmm
